let CATEGORIES = [
    "beach",
    "beach.beach_resort",
    "camping",
    "entertainment",
    "entertainment.culture",
    "entertainment.culture.theatre",
    "entertainment.culture.gallery",
    "entertainment.museum",
    "entertainment.cinema",
    "entertainment.theme_park",
    "entertainment.water_park",
    "entertainment.zoo",
    "entertainment.aquarium",
    "leisure",
    "leisure.park",
    "leisure.playground",
    "natural",
    "natural.forest",
    "natural.water",
    "natural.mountain",
    "national_park",
    "ski",
    "sport",
    "sport.stadium",
    "sport.swimming_pool",
    "tourism",
    "tourism.attraction",
    "tourism.sights",
    "tourism.information",
    "heritage",
    "commercial.supermarket",
    "commercial.shopping_mall",
    "commercial.clothing",
    "commercial.gift_and_souvenir",
    "commercial.food_and_drink",
    "catering.restaurant",
    "catering.fast_food",
    "catering.cafe"
]


  export default CATEGORIES
